/**
 * ───「 INFO SCRAPER 」───
 * 📝 Adaptasi  : LYNX DECODE (Erine-MD)
 * ───────────────────────
 */

import fetch from 'node-fetch';

const ORIGIN = "https://app.blackbox.ai";
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36 Edg/149.0.0.0";
const FALLBACK_VALIDATED = "a38f5889-8fef-46d4-8ede-bf4668b6a9bb";
const ANCHOR = /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})";function detectVscode/;
const WRAP_SYSTEM = "Wrap your entire reply between <answer> and </answer> tags. Write nothing outside these tags.";
const OPEN_TAG = /^(?:<answer>|answer>|nswer>|swer>|wer>|er>|r>|>)\s*/;

let cachedValidated = FALLBACK_VALIDATED;

function randomId(len = 7) {
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let s = "";
    for (let i = 0; i < len; i++) s += chars[Math.floor(Math.random() * chars.length)];
    return s;
}

function isRejected(raw) {
    return /Generated by BLACKBOX\.AI|not upgraded your account/i.test(raw);
}

function parseAnswer(raw) {
    const think = [];
    let body = raw.replace(/<think>([\s\S]*?)<\/think>/g, (_, t) => {
        think.push(t.trim());
        return "";
    });
    const end = body.indexOf("</answer>");
    if (end !== -1) body = body.slice(0, end).trimStart().replace(OPEN_TAG, "");
    return { text: body.trim(), think: think.join("\n\n").trim() || null };
}

async function fetchValidated() {
    const headers = { "user-agent": UA };
    const html = await fetch(`${ORIGIN}/`, { headers }).then(r => r.text()).catch(() => "");
    const chunks = [...new Set([...html.matchAll(/\/_next\/static\/[^"]+\.js/g)].map(m => m[0]))];
    const found = await Promise.all(chunks.map(c =>
        fetch(`${ORIGIN}${c}`, { headers })
            .then(r => r.text())
            .then(js => (js.match(ANCHOR) || [])[1] || null)
            .catch(() => null)
    ));
    return found.find(Boolean) || null;
}

function buildPayload(messages, validated, options) {
    const { webSearch = false, agent = "VscodeAgent", maxTokens = 1024 } = options;
    return {
        messages,
        id: messages[messages.length - 1].id,
        userSelectedAgent: agent,
        userSelectedModel: null,
        maxTokens,
        validated,
        clickedForceWebSearch: webSearch,
        webSearchModeOption: { autoMode: !webSearch, webMode: webSearch, offlineMode: false },
        codeModelMode: true,
        isPremium: false
    };
}

async function request(payload) {
    const res = await fetch(`${ORIGIN}/api/chat`, {
        method: "POST",
        headers: {
            "content-type": "application/json",
            "origin": ORIGIN,
            "referer": `${ORIGIN}/chat`,
            "user-agent": UA
        },
        body: JSON.stringify(payload)
    });
    return res.text();
}

const blackboxChat = async (prompt, options = {}) => {
    try {
        const history = Array.isArray(options.history) ? options.history : [];
        const userMsg = { id: randomId(), role: "user", content: String(prompt) };
        const wrapped = [{ id: randomId(), role: "system", content: WRAP_SYSTEM }, ...history, userMsg];

        let raw = await request(buildPayload(wrapped, cachedValidated, options));

        if (isRejected(raw)) {
            const fresh = await fetchValidated();
            if (fresh && fresh !== cachedValidated) {
                cachedValidated = fresh;
                raw = await request(buildPayload(wrapped, cachedValidated, options));
            }
        }

        if (isRejected(raw)) throw new Error(raw.trim());

        const { text, think } = parseAnswer(raw);
        return {
            ok: true,
            text,
            think,
            validated: cachedValidated,
            history: [...history, userMsg, { id: randomId(), role: "assistant", content: text }]
        };
    } catch (error) {
        throw new Error(error.message);
    }
};

export default blackboxChat;